### ISSUE TITLE
typescript definition files open blank file referencing a file in git repo

### ISSUE THREAD

**Issue by ungb** [atom/ide-typescript#10]
Repro Steps:

1. Open atom repo
2. Open file: `/src/atom-paths.js` in the atom repo
3. cmd/ctrl click the method `toISOString` on line 9.

Findings: Opens a blank file with path of https://github.com/Microsoft/TypeScript?v2.3.4#lib/lib.d.ts

See Gif:

![openblank](https://user-images.githubusercontent.com/5624870/29591815-b39b1c10-8755-11e7-8e55-34871ca7dbf1.gif)

**Comment by damieng** [comment]
The bug part of this where we do not attempt to turn https and http into paths is fixed at https://github.com/atom/atom-languageclient/commit/6f1e149c052888ff00c26b79be66e7bc7109d84f

However we still need to add support to Atom for loading file over http and https.

**Comment by akaRem** [comment]
@damieng 
I jumped into the same problem. But it's more than just failing on http/https as you mentioned previously.

I'm using Atom v1.20.1 with ide-typescript v0.1.6 on macos 10.11.6 with node v8.4.0.
I have project with TS installed as project dependency and TS that is installed globally.
Both of them are v2.5.2 

If I jump to def of Promise (for example) Atom tries to open `git:/github.com/Microsoft/TypeScript?v2.4.2#lib/lib.es6.d.ts` and fails. 
I also want to mention that git protocol is used here (and you can see this in animation from first post).
And btw in my case it suggests 4 urls to jump to:
<img width="527" alt="2017-09-30 22 50 47" src="https://user-images.githubusercontent.com/1472728/31048947-d3ea7146-a631-11e7-935e-1d02fe13bb84.png">
..and these urls are started with `git://..` whereas it opens `git:/...` (with one slash) and this could be a part of the issue.

But I see another problem here that is much more bigger from my point of view.

Ide-typescript tries to open `d.ts` files for other version of TS (2.4.2) than I use (2.5.2) and this is not correct.
I have an assumption that this problem comes from the fact that ide-typescript depends on javascript-typescript-langserver that depends on typescript v2.4.2.
I also have an assumption that all TS checks are performed against TS v2.4.2 and not TS v2.5.2. 

This problem is not big deal for my case — v2.5 has just few new features in comparison with v2.4. But anyway new TS features are unavailable until javascript-typescript-langserver will update its dependencies. And if anyone uses version older than than 2.4 in their projects they are in trouble too.

In VSCode this case is handled by local files (depending on which TS installation is selected)
For globally installed TS it searches d.ts files somewhere in
`/usr/local/lib/node_modules/typescript/lib/lib.es6.d.ts`
For TS added in project it searches somewhere in
`<project path>/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts`.
I think that this is very sane and fixes any issues of such kind.

**Comment by akaRem** [comment]
here https://github.com/atom/ide-typescript/issues/30#issuecomment-330797989 is mentioned that langserver doesn't respect tsconfig. So it could be additional problem for resolving lib path and picking correct d.ts files.

**Comment by damieng** [comment]
Actual url for the file is https://github.com/Microsoft/TypeScript/blob/v2.3.4/lib/lib.d.ts

**Comment by mattlyons0** [comment]
On version 0.8 ctrl-clicking `toISOString()` opens the typescript interface file correctly: ![screenshot](https://i.imgur.com/YqnE83j.png)

**Comment by damieng** [comment]
Great!
