### ISSUE TITLE
ES next

### ISSUE THREAD

**Issue by jchouse** [atom/ide-typescript#31]
How about ES next? 
<img width="517" alt="screen shot 2017-09-14 at 14 01 49" src="https://user-images.githubusercontent.com/1298726/30426754-e06d22e4-9955-11e7-8fb3-f3c995ac66e7.png">

**Comment by damieng** [comment]
We're dependent on the TypeScript compiler for our language services. Their position has they support the actual standard rather than stuff that is not ratified or still at proposal stage.

It looks like the :: bind operator has never got past the initial proposal.

Further discussion can be found at https://github.com/Microsoft/TypeScript/issues/3508
