### ISSUE TITLE
Missing support for code highlight

### ISSUE THREAD

**Issue by nothingrandom** [atom/ide-typescript#49]
See this issue > https://github.com/facebook-atom/atom-ide-ui/issues/31

**Comment by damieng** [comment]
The [underlying language server](https://github.com/sourcegraph/javascript-typescript-langserver/) we use for code highlight does not support the codeHighlight feature.

Not all features will be available in all languages because of this. You can try filing a feature request for this on [javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver/)
