### ISSUE TITLE
Update on Windows fails (Device or resource busy)

### ISSUE THREAD

**Issue by amejia1** [atom/ide-typescript#88]
Updating ide-typescript on Windows fails with the error being a device or resource was busy. This normally happens when I have a JS project opened. The workaround is to completely shutdown Atom and update using apm.

Since this package uses a language server, this might be related to https://github.com/atom/apm/issues/743 , but I'm reporting it here in case it's not.

**Comment by rsese** [comment]
Thanks for the report - looks like an issue was opened for this in https://github.com/atom/ide-typescript/issues/36 and Damien confirms that you can't update while the language server is running /cc https://github.com/atom/ide-typescript/issues/36#issuecomment-369406840 (though closing all .ts and .js files seems to be enough rather than restarting Atom).
